/* Smoke tests: expansion integrity + DOM wiring between index.html and js/app.js.
   Usage: node tools/smoke.mjs */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const win = {};
globalThis.window = win;
const load = rel => new Function('window', readFileSync(join(root, rel), 'utf8'))(win);

for (const f of ['data/games.js', 'data/apps.js', 'data/websites.js', 'js/expand.js']) load(f);

let fail = 0;
const ok = (cond, msg) => { if (!cond) { console.error('  ✗ ' + msg); fail++; } };

/* ---------------------------------------------------- 1. expansion integrity */
const RAW = win.RAW, IF = win.IdeaForge;
const ALL = [...IF.build(RAW.games, 'games'), ...IF.build(RAW.apps, 'apps'), ...IF.build(RAW.websites, 'websites')];
console.log(`\nExpansion — ${ALL.length} records`);

const required = ['id', 'title', 'category', 'stack', 'hook', 'loop', 'twist', 'levels', 'spark',
  'whyAddictive', 'infiniteDesign', 'depth', 'artDirection', 'firstMinute', 'sessionShape',
  'monetisation', 'priorArt', 'controlsDetail', 'searchText', 'plain', 'tldr'];

for (const it of ALL) {
  for (const f of required) ok(it[f] && String(it[f]).trim().length > 0, `${it.id} empty field: ${f}`);
  ok(it.tags.length >= 2, `${it.id} has fewer than 2 tags`);
  ok(it.prototype.length >= 5, `${it.id} prototype plan too short`);
  ok(it.retention.length >= 2, `${it.id} retention too thin`);
  ok(it.pitfalls.length >= 2, `${it.id} pitfalls too thin`);
  ok(it.plain.split('\n').length >= 20, `${it.id} plain text too short (${it.plain.split('\n').length} lines)`);
  ok(it.plain.includes(it.title) && it.plain.includes(it.hook), `${it.id} plain text missing title/hook`);
  ok(!/\bundefined\b|\bNaN\b|\[object/.test(it.plain), `${it.id} plain text contains undefined/NaN`);
  ok(it.infiniteDesign.length > 80, `${it.id} levels/endlessness too short (${it.infiniteDesign.length})`);
}

/* determinism: same input, same output */
const a = IF.build(RAW.games.slice(0, 3), 'games')[0].whyAddictive;
const b = IF.build(RAW.games.slice(0, 3), 'games')[0].whyAddictive;
ok(a === b, 'expansion is not deterministic');

/* markdown export works */
for (const it of [ALL[0], ALL[700], ALL[1200]]) {
  const md = IF.toMarkdown(it);
  ok(md.length > 400 && md.startsWith('### '), `${it.id} markdown export malformed`);
}

/* variety: how many distinct phrasings does the engine actually produce? */
const uniq = (arr) => new Set(arr).size;
console.log(`  distinct why-addictive phrasings: ${uniq(ALL.map(i => i.whyAddictive))}`);
console.log(`  distinct art directions:          ${uniq(ALL.map(i => i.artDirection))}`);
console.log(`  distinct infinite-design:         ${uniq(ALL.map(i => i.infiniteDesign))}`);
console.log(`  distinct monetisation:            ${uniq(ALL.map(i => i.monetisation))}`);

/* --------------------------------------------------------- 2. DOM wiring */
const html = readFileSync(join(root, 'index.html'), 'utf8');
const appjs = readFileSync(join(root, 'js/app.js'), 'utf8');
const htmlIds = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map(m => m[1]));
const used = new Set([...appjs.matchAll(/\$\('#([A-Za-z0-9_-]+)'\)/g)].map(m => m[1]));
console.log(`\nDOM wiring — ${htmlIds.size} ids in HTML, ${used.size} referenced by app.js`);
for (const id of used) ok(htmlIds.has(id), `app.js references #${id} which is not in index.html`);

/* every class app.js queries must exist in the HTML or be generated by app.js */
const htmlClasses = new Set([...html.matchAll(/class="([^"]+)"/g)].flatMap(m => m[1].split(/\s+/)));
const queried = new Set([...appjs.matchAll(/\$\$?\('\.([A-Za-z0-9_-]+)'\)/g)].map(m => m[1]));
for (const c of queried) {
  const generated = new RegExp(`class="[^"]*\\b${c}\\b`, 'g').test(appjs);
  ok(htmlClasses.has(c) || generated, `app.js queries .${c} which is never rendered`);
}

/* script/style references exist */
for (const m of html.matchAll(/(?:src|href)="((?!http|data:|#)[^"]+)"/g)) {
  const p = join(root, m[1]);
  try { readFileSync(p); } catch { console.error(`  ✗ index.html references missing file: ${m[1]}`); fail++; }
}

/* ------------------------------------------------- 2b. hidden-attribute guard */
/* Author CSS beats the UA stylesheet, so `.overlay{display:flex}` silently wins
   over `[hidden]{display:none}` and leaves every overlay covering the page.
   That shipped once. A global [hidden] rule with !important is the only safe fix. */
const css = readFileSync(join(root, 'css/styles.css'), 'utf8');
const hiddenEls = [...html.matchAll(/<[^>]*\shidden(?=[\s>])[^>]*>/g)];
console.log(`\nHidden-attribute guard — ${hiddenEls.length} elements carry [hidden]`);
ok(hiddenEls.length > 0, 'expected some elements to use the hidden attribute');
ok(/\[hidden\]\s*\{[^}]*display\s*:\s*none\s*!important/.test(css),
  'css/styles.css needs a global `[hidden]{display:none !important}` rule, ' +
  'otherwise any class with a display property will render despite [hidden]');
/* any class on a [hidden] element that also sets display is the dangerous case */
for (const m of hiddenEls) {
  const tag = m[0];
  const cls = (tag.match(/class="([^"]+)"/) || [, ''])[1].split(/\s+/).filter(Boolean);
  for (const c of cls) {
    const rule = new RegExp(`\\.${c}\\s*\\{[^}]*display\\s*:`, 'g');
    if (rule.test(css)) {
      ok(/\[hidden\]\s*\{[^}]*display\s*:\s*none\s*!important/.test(css),
        `.${c} sets display and is used with [hidden] — needs the global !important rule`);
    }
  }
}

/* --------------------------------------------------------- 3. JS syntax */
import { execSync } from 'node:child_process';
for (const f of ['js/app.js', 'js/expand.js', 'sw.js']) {
  try { execSync(`node --check ${join(root, f)}`, { stdio: 'pipe' }); }
  catch (e) { console.error(`  ✗ syntax error in ${f}: ${e.stderr}`); fail++; }
}

console.log(fail ? `\nFAILED with ${fail} problem(s)\n` : '\nAll smoke tests passed\n');
process.exit(fail ? 1 : 0);
